sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
  global:
  - secure: LwaFRF8Tu1mTMljym/3nou1YojBS4Su72B6Hk7Au+wfAj6Nnkw/o+QFjg3kPu1EIZ7SlKxnSQqjgsqWVNM2CmrgrarqOocPFFm7svQIa2CwZPA9ZOAIY6k9uSpI1stgvdVHU338gRM7lhxuPnk3rK3it/VOFrG2H0KhCIwQuZ81KkZ5ykVK8SRUQ8RowMwx5kAp9g5gnlVKIrQq/By+v1vbmsmY321jZpBYLFpAWh2JcVTxG0ywx0JM9Kidb4sjQXN7ffYD2fnLoc91zzvw441REx3HI0xCbeMihfMu+0xjObMhLmF04C7jOH56Fvm5RhTrbHrq/sN8uVM/5F+9dYglJZaZyn7WLRyVXdKP4AF6Mq2MLF7HQgzJqAVYqKkVziJN58O8KWv4qiDWVLX2dQt8GztByQBc+yq6zcff3+0S526pb+CPWUyo3RCDPcTffmYrSQlNOn13LXgy030dQrgnOjDAy+8np/nUMQ+1czsOJdQyvag6W0HWtoi4Ba6yLNsixvGFMoJE3YMBPuTcLLRbEcIToh6GN6uxybtgD9FdXU2n3mqRQpLpyz6iwluR4dx4PNn7IN0gmzAe6bU1nVT9SsZYS0q87TF7Jsesr1C74Jk4nT0aRET4ip6tfa8LIfgBvfKTyDYhagAQXLkjLiWeuAwYefS2tjJtAjGAFCAg=
  - secure: D3ND4HGS0t86JIj7/gVSf9dvGq530tjt0zgpguVXmqsY3wVRlatHBWtsnFB+REurIoJyFD6IR/9zHjyWMczKw9Oev1Iz0G5ztzE3yeqIGkWUjDxJGePn2tFO7k7B+ZwTpJiZiOpdiQa9Yb1RzNVwgoIZHMXwrQzWvAhLlzHykp9kb1to4YvQI54G7Vu4WjVbmGIK/fkskHPzsj3EG/okvguOLv9yWq/vJ3C2i1RtH2c1mpbmp31lr9XH3JSXlwcCybx2a+zlsJH+JEFkSkNeSihYyJc3T8kq5+9UqV3gSRenZmwTSVBaFAJrZat636bKJIEOlTpS6qt0YKNsc7L8jrSIPZ3t9oiFwJ958wukphlxCwFaXMeg5QqIgdxkJBZMt0J3fToACpn65iamXmM+OjUro0gIwwihLbN2mIwax/bPBHxqxwLjS0f8JzZX/dRb/TLt3LiEK7UBUHftnFe640WWGtTAbNkidYNro+iUobfUzYfxO6y7R8BSm1+xGSqK4VeDlMlF/vPsxxC+LBRCx0V4b2gp4/lweEYZXX537JqRRfFeeqPwStyyfZw/W5BRw8GhaE0MCkcLQWiY2AW3xXf6F2VgyQ/v+73WtHpw6m9ZpgkYNEVjo3UAI7IqxQonqnGK0f5rCmiBS6khCJbuofbDX8ujpMmwFqiGW0ppWeI=
notifications:
  email: false
